### ISSUE TITLE
Incorrect parsing of dates

### ISSUE THREAD

**Issue by cfbevan** [fashion-js/fashion-model#14]
Dates with long millisecond precision are being parsed incorrectly.

Test Code

```javascript
const Model = require("fashion-model/Model");

const Document = Model.extend({
  properties: {
    dateCreated: Date,
  },
});

const input = "2022-01-10T21:15:41.573740635Z";

const document = new Document();
document.setDateCreated(input);
console.log(document.stringify());
```

Actual Output

```
{"dateCreated":"2022-01-17T12:38:01.635Z"}
```

Expected Output

```
{"dateCreated":"2022-01-10T21:15:41.573Z"}
```

**Comment by philidem** [comment]
@cfbevan what library is formatting dates as strings like this? The JavaScript `Date` object doesn't natively support nanosecond precision. The last part is assumed to be in milliseconds (in the range of 0-999).

The `new Date("2022-01-10T21:15:41.573740635Z")` method of parsing (which wasn't properly supported across all browsers and Node.js when this parsing logic was written) seems to truncate `573740635`  to `573` which might not be what you expect either.

```
> new Date("2022-01-10T21:15:41.573740635Z").toISOString()
'2022-01-10T21:15:41.573Z'
```

**Comment by cfbevan** [comment]
It is not coming from a library. It is raw string input from `docker inspect` when attempting to parse the creation date of an image.

**Comment by austinkelleher** [comment]
@philidem @bishopb @cfbevan Here is my proposed fix: https://github.com/fashion-js/fashion-model/pull/15

NOTE: This project has been used for years across many Node.js versions. Unfortunately, there are no indicators in the project that point to which Node.js versions are supported. According to MDN, `Date.parse` is supported in Node 0.10.0, so it should be safe to use.

We may want to major version and push forward with testing against modern Node.js versions in CI (e.g. 14.x, 16.x).
